//
// Created by Jonathan Rumion on 5/28/15.
//

#ifndef ASPACEOPERA_WIDGETIDS_H
#define ASPACEOPERA_WIDGETIDS_H

const int ID_CONNECT = 2600;
const int ID_DISCONNECT = 2601;
const int ID_CENTERMASTERWINDOW = 2602;
const int ID_SAVEPERSPECTIVE = 2603;
const int ID_LOADPERSPECTIVE = 2604;



#endif //ASPACEOPERA_WIDGETIDS_H
